// styles/GlobalStyles.ts
import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = width - 40;

const colors = {
  background: "#F1F5F6",
  surface: "#FFFFFF",
  text: "#102A43",
  muted: "#627D98",
  primary: "#0F766E",
  primarySoft: "#DFF5F1",
  accent: "#F59E0B",
  border: "#D9E2EC",
};

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    paddingTop: 8,
  },
  navBar: {
    flexDirection: "row",
    height: 84,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    paddingBottom: 20,
    shadowColor: "#0B1F33",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 8,
  },
  navItem: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 14,
    marginHorizontal: 6,
    marginTop: 6,
  },
  navText: {
    fontSize: 10,
    color: colors.muted,
    marginTop: 4,
    fontWeight: "600",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  activeNavText: {
    color: colors.primary,
    fontWeight: "800",
  },
  headerRow: {
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  dateText: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.text,
    marginBottom: 12,
    letterSpacing: 0.4,
  },
  weatherCard: {
    backgroundColor: colors.primary,
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#004D40",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  tempText: {
    fontSize: 34,
    fontWeight: "900",
    color: "#F8FAFC",
    marginRight: 14,
  },
  weatherDesc: {
    flex: 1,
    color: "#ECFEFF",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  ootdSection: {
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 16,
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: colors.text,
    marginBottom: 12,
    letterSpacing: 0.6,
  },
  ootdContainer: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    minHeight: 360,
    padding: 18,
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#0B1F33",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  placeholderOutfit: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  shuffleButton: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 44,
    borderRadius: 999,
    marginTop: 8,
    shadowColor: "#A16207",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  shuffleText: {
    color: "#1A1300",
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  topIcons: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  row: { flexDirection: "row", alignItems: "center" },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  wardrobeLabel: {
    fontSize: 12,
    color: colors.muted,
    letterSpacing: 2,
    fontWeight: "700",
  },
  wardrobeTitle: {
    fontSize: 34,
    fontWeight: "900",
    color: colors.text,
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
  },
  addText: {
    color: "#F8FAFC",
    marginRight: 8,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 18,
  },
  gridItem: {
    width: "48%",
    marginBottom: 18,
  },
  itemImagePlaceholder: {
    height: 150,
    backgroundColor: "#D9E2EC",
    borderRadius: 14,
    marginBottom: 8,
  },
  itemBar: {
    height: 4,
    backgroundColor: colors.primary,
    borderRadius: 999,
    marginTop: 10,
    marginBottom: 6,
    width: "48%",
  },
  itemBarShort: {
    height: 6,
    backgroundColor: colors.border,
    width: "60%",
    borderRadius: 3,
  },
  pageTitle: {
    fontSize: 24,
    padding: 20,
    fontWeight: "700",
    color: colors.text,
  },
  imageFull: { height: 200, backgroundColor: colors.border, borderRadius: 15 },
  articleSub: { color: colors.muted, fontSize: 12 },
  headerIconRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 8,
    marginBottom: 4,
  },
  logoTextSmall: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: 0.4,
    lineHeight: 30,
  },
  headerIcon: {
    width: 52,
    height: 52,
  },
  wardrobeImage: {
    width: "100%",
    height: 164,
    borderRadius: 16,
    backgroundColor: "#D9E2EC",
    borderWidth: 1,
    borderColor: colors.border,
  },
  cameraFullContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  cameraOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
    justifyContent: "space-between",
    padding: 36,
    paddingTop: 58,
  },
  cameraTopBar: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  cameraBottomBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  autoText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
  },
  cancelText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "600",
  },
  shutterButton: {
    width: 78,
    height: 78,
    borderRadius: 40,
    backgroundColor: "#fff",
    padding: 5,
  },
  shutterInner: {
    flex: 1,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "#111827",
  },
  confirmOverlay: {
    position: "absolute",
    bottom: 100,
    width: "100%",
    alignItems: "center",
  },
  confirmBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 48,
    borderRadius: 999,
    marginBottom: 18,
  },
  confirmText: {
    color: "#F8FAFC",
    fontWeight: "800",
    fontSize: 16,
  },
  fullPreview: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  carouselHeight: {
    height: 250,
  },
  carouselImage: {
    width: CARD_WIDTH,
    height: 250,
    resizeMode: "cover",
  },
  swipeHint: {
    fontSize: 10,
    color: colors.primary,
    marginTop: 10,
    fontWeight: "700",
    textAlign: "right",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  articleCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    marginBottom: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
  },
  paddingContainer: {
    padding: 20,
  },
  trendingTitle: {
    fontSize: 34,
    fontWeight: "900",
    color: colors.text,
    marginBottom: 20,
  },
  trendingSectionTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.text,
    marginTop: 30,
    marginBottom: 12,
  },
  subBrandTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 15,
    textAlign: "center",
  },
  carouselContainer: {
    paddingRight: 8,
  },
  carouselItemFrame: {
    marginRight: 15,
  },
  rawCarouselImage: {
    width: 280,
    height: 180,
    borderRadius: 20,
  },
  fashionWeekSection: {
    marginBottom: 24,
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    shadowColor: "#0B1F33",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  fashionWeekImage: {
    width: "100%",
    height: 220,
  },
  fashionWeekContent: {
    marginTop: 12,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  articleTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.text,
    marginBottom: 6,
  },
  articleDescription: {
    fontSize: 14,
    color: colors.muted,
    lineHeight: 21,
    marginBottom: 6,
  },
  authorText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  detailImage: {
    width: "100%",
    height: 350,
    backgroundColor: "#E4ECEE",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  detailContent: {
    padding: 24,
  },
  detailType: {
    fontSize: 30,
    fontWeight: "900",
    color: colors.text,
    marginBottom: 6,
  },
  detailColor: {
    fontSize: 16,
    color: colors.muted,
    marginTop: 4,
    fontWeight: "600",
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 20,
  },
  descriptionLabel: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.text,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  descriptionText: {
    fontSize: 15,
    color: colors.muted,
    lineHeight: 22,
  },
  addToOutfitBtn: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 24,
  },
  addToOutfitText: {
    color: "#F8FAFC",
    fontWeight: "800",
    fontSize: 16,
  },
  backButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
  },
  backText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  containerCenter: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  logoText: {
    fontSize: 52,
    fontWeight: "900",
    color: colors.text,
    lineHeight: 52,
    letterSpacing: 0.6,
  },
  mainIcon: {
    width: 180,
    height: 180,
    marginVertical: 26,
  },
  welcomeText: {
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 4,
    color: colors.muted,
    marginBottom: 30,
    textTransform: "uppercase",
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 999,
    shadowColor: "#0F766E",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  buttonText: {
    color: "#F8FAFC",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  heroCard: {
    width: "100%",
    height: 240,
    borderRadius: 15,
    overflow: "hidden",
    marginBottom: 25,
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  outfitGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  gridArticle: {
    width: "48%",
    marginBottom: 20,
  },
  gridImageWrapper: {
    height: 120,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#f1f5f9",
  },
  gridImage: {
    width: "100%",
    height: "100%",
  },
  gridTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 8,
  },
  gridDesc: {
    fontSize: 12,
    color: colors.muted,
    marginVertical: 4,
  },
  gridMeta: {
    fontSize: 10,
    color: colors.muted,
  },
  expandIcon: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "white",
    padding: 5,
    borderRadius: 5,
  },
  expandIconSmall: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "white",
    padding: 2,
    borderRadius: 3,
  },
  outfitMainTitle: {
    fontSize: 32,
    color: colors.text,
    fontWeight: "700",
    textAlign: "center",
    marginVertical: 25,
  },
  outfitWrapper: {
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 15,
  },
  outfitCard: {
    width: "100%",
  },
  outfitImageContainer: {
    width: "100%",
    height: 220,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  outfitImg: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  outfitTextContent: {
    marginTop: 15,
  },
  outfitTitleText: {
    fontSize: 22,
    fontWeight: "600",
    color: colors.text,
  },
  outfitDescText: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 5,
    lineHeight: 20,
  },
  outfitMetaText: {
    fontSize: 12,
    color: colors.text,
    marginTop: 8,
  },
  clothesListDropdown: {
    backgroundColor: "#f8fafc",
    marginTop: 10,
    borderRadius: 10,
    padding: 15,
  },
  listHeader: {
    fontWeight: "bold",
    marginBottom: 10,
    color: colors.primary,
  },
  clothingListItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7FAFC",
    padding: 10,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  miniThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  miniText: {
    marginLeft: 12,
    flex: 1,
    fontWeight: "700",
    color: colors.text,
  },
  viewMoreArrow: {
    color: colors.primary,
    fontWeight: "bold",
  },
  expandIconOverlay: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 22,
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(7,19,33,0.92)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCloseArea: {
    ...StyleSheet.absoluteFillObject,
  },
  fullImageContainer: {
    width: "90%",
    height: "80%",
    justifyContent: "center",
    alignItems: "center",
  },
  fullViewImage: {
    width: "100%",
    height: "100%",
  },
  closeButton: {
    marginTop: 20,
    backgroundColor: colors.surface,
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 999,
  },
  closeButtonText: {
    color: colors.text,
    fontWeight: "800",
  },
  hintText: {
    fontSize: 14,
    color: colors.primary,
    marginTop: 10,
  },
  outfitDisplay: {
    flex: 1,
    width: "100%",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingVertical: 8,
  },
  outfitItem: {
    width: "100%",
    alignItems: "center",
    marginBottom: 6,
    padding: 6,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
  },
  outfitItemImage: {
    width: 98,
    height: 98,
  },
  outfitItemLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primary,
    textAlign: "center",
  },
  noOutfitText: {
    fontSize: 15,
    color: colors.muted,
    textAlign: "center",
    paddingHorizontal: 20,
    lineHeight: 22,
  },
  itemText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
    marginTop: 5,
  },
  itemSubText: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
    textTransform: "capitalize",
  },
  previewImage: {
    width: "100%",
    height: 300,
    borderRadius: 20,
    marginBottom: 20,
  },
  input: {
    backgroundColor: "#F8FAFC",
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    fontSize: 16,
  },
  rowclothedit: {
    flexDirection: "row",
    marginBottom: 20,
  },
  chip: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F8FAFC",
    marginRight: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  activeChip: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    color: colors.muted,
    fontWeight: "700",
  },
  activeChipText: {
    color: "#fff",
  },
  changePhotoOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 20,
  },
  trendingBadge: {
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    position: "absolute",
    top: 10,
    left: 10,
  },
  trendingBadgeText: {
    fontSize: 10,
    color: colors.primary,
    fontWeight: "800",
    letterSpacing: 0.7,
  },
});
